secretsanta/urls.py
from django.urls import path

from . import views

app_name = "secretsanta"

urlpatterns = [
    path("", views.index, name="index"),
    path("apply/<int:year>/", views.apply, name="apply"),
    path("mark_received/<int:year>/", views.mark_received, name="mark_received"),
    path("pairs/<int:year>/", views.pairs, name="pairs"),
    path("applications/<int:year>/", views.applications, name="applications"),
    path("generate_pairs/<int:year>/", views.queue_generate_pairs, name="generate_pairs"),
    path("notify_santas/<int:year>/", views.queue_notify_santas, name="notify_santas"),
    path("notify_outstanding_santees/<int:year>/", views.queue_notify_outstanding_santees, name="notify_outstanding_santees"),
]

secretsanta/templates/secretsanta/applications.html
{% extends "secretsanta/base.html" %}
{% load i18n %}
{% load humanize %}
{% block details %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{% translate "Secret Santa Applications" %}</h3>
        </div>
        <div class="panel-body">
            <table class="table table-hover" id="table-secret-santa-applications">
                <thead>
                    <tr>
                        <th class="text-left">{% translate "Application" %}</th>
                        <th class="text-left">{% translate "Manage" %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for application in applications %}
                        <tr>
                            <td>{{ application.user.profile.main_character }}</td>
                            <td>put some buttons here</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% if year.open %}
        <a class="btn btn-danger" href="{% url 'secretsanta:generate_pairs' year.year %}" role="button">
            <span class="fa fas fa-skull-crossbones"></span>{% trans "Generate Pairs" %}<span class="fa fas fa-skull-crossbones"></span></a>
    {% endif %}
{% endblock details %}
{% block extra_javascript %}
    {% include "bundles/datatables-js.html" %}
    {% include "bundles/moment-js.html" %}
{% endblock extra_javascript %}
{% block extra_css %}
    {% include "bundles/datatables-css.html" %}
{% endblock extra_css %}
{% block extra_script %}
    $(document).ready( function () {
    $('#table-secret-santa-applications').DataTable({
    lengthMenu: [
    [10, 25, 50, 100, -1],
    [10, 25, 50, 100, 'All'],
    ],
    "stateSave": true,
    "stateDuration": 0
    });
    } );
{% endblock extra_script %}

secretsanta/templates/secretsanta/base.html
{% extends "allianceauth/base.html" %}
{% load i18n %}
{% load humanize %}
{% load static %}
{% block page_title %}
    {% translate "Secret Santa" %}
{% endblock page_title %}
{% block content %}
    <div class="container-fluid aa-secret-santa">
        <br />
        <nav class="navbar navbar-default">
            <div class="navbar-header">
                <button type="button"
                        class="navbar-toggle collapsed"
                        data-toggle="collapse"
                        data-target="#secret-santa-navbar-collapse-1"
                        aria-expanded="false">
                    <span class="sr-only">{% trans "Toggle navigation" %}</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'secretsanta:index' %}">{% trans "Secret Santa" %}</a>
            </div>
            <div class="collapse navbar-collapse" id="secret-santa-navbar-collapse-1"></div>
        </nav>
        {% block details %}
        {% endblock details %}
    </div>
{% endblock content %}

secretsanta/templates/secretsanta/index.html
{% extends "secretsanta/base.html" %}
{% load i18n %}
{% load humanize %}
{% block details %}
    <div class="row">
        {% for year in year_renders %}{{ year }}{% endfor %}
    </div>
{% endblock details %}

secretsanta/templates/secretsanta/pairs.html
{% extends "secretsanta/base.html" %}
{% load i18n %}
{% load humanize %}
{% block details %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{% translate "Secret Santa Pairs" %}</h3>
        </div>
        <div class="panel-body">
            <table class="table table-hover" id="table-secret-santa-pairs">
                <thead>
                    <tr>
                        <th class="text-left">{% translate "Santa" %}</th>
                        <th class="text-left">{% translate "Santee" %}</th>
                        <th class="text-left">{% translate "Delivered" %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for pair in pairs %}
                        <tr>
                            <td>{{ pair.santa.profile.main_character }}</td>
                            <td>{{ pair.santee.profile.main_character }}</td>
                            <td>{{ pair.delivered }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% if year.open %}
    {% else %}
        <a class="btn btn-warning" href="{% url 'secretsanta:notify_santas' year.year %}" role="button"><span class="fa fas fa-skull-crossbones"></span>{% trans "notify_santas" %}<span class="fa fas fa-skull-crossbones"></span></a>
        <a class="btn btn-info" href="{% url 'secretsanta:notify_outstanding_santees' year.year %}" role="button"><span class="fa fas fa-skull-crossbones"></span>{% trans "notify_outstanding_santees" %}<span class="fa fas fa-skull-crossbones"></span></a>
    {% endif %}
{% endblock details %}
{% block extra_javascript %}
    {% include "bundles/datatables-js.html" %}
    {% include "bundles/moment-js.html" %}
{% endblock extra_javascript %}
{% block extra_css %}
    {% include "bundles/datatables-css.html" %}
{% endblock extra_css %}
{% block extra_script %}
    $(document).ready( function () {
    $('#table-secret-santa-pairs').DataTable({
    lengthMenu: [
    [10, 25, 50, 100, -1],
    [10, 25, 50, 100, 'All'],
    ],
    "stateSave": true,
    "stateDuration": 0
    });
    } );
{% endblock extra_script %}

secretsanta/templates/secretsanta/year.html
{% load i18n %}
<div class="col-lg-3">
    {% if year.open %}
        <div class="panel panel-info">
            <div class="panel-heading">
                <div class="panel-title">{{ year.year }}</div>
            </div>
            <div class="panel-body">
                {% trans "Members" %}: <span class="label label-primary">{{ year.members }}</span>
                <br />
                {% trans "Santee" %}: <span class="label label-primary">{{ users_santee }}</span>
                <br />
                <br />
                {% if application_exists %}
                    <span class="btn btn-info" role="button" disabled="disabled">{% trans "Joined" %}</span>
                {% else %}
                    <a class="btn btn-info" href="{% url 'secretsanta:apply' year.year %}" role="button">{% trans "Join" %}</a>
                {% endif %}
                {% if year.participating %}
                    <a class="btn btn-info" href="{% url 'secretsanta:mark_received' year.year %}" role="button">{% trans "Received Gift" %}</a>
                {% endif %}
                {% if perms.secretsanta.manage %}
                    <a class="btn btn-warning" href="{% url 'secretsanta:applications' year.year %}" role="button">{% trans "Applications" %}</a>
                    <a class="btn btn-danger" href="{% url 'secretsanta:pairs' year.year %}" role="button"><span class="fa fas fa-skull-crossbones"></span> {% trans "Administer" %} <span class="fa fas fa-skull-crossbones"></span></a>
                {% endif %}
            </div>
        </div>
    {% else %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title">{{ year.year }}</div>
            </div>
            <div class="panel-body">
                {% trans "Members" %}: <span class="label label-primary">{{ year.members }}</span>
                <br />
                {% trans "Santee" %}: <span class="label label-primary">{{ users_santee }}</span>
                <br />
                <br />
                {% if santapair_exists %}
                    {% if gift_delivered %}
                        <span class="btn btn-info" disabled="disabled" role="button">{% trans "Received Gift" %}</span>
                    {% else %}
                        <a class="btn btn-info" href="{% url 'secretsanta:mark_received' year.year %}" role="button">{% trans "Received Gift" %}</a>
                    {% endif %}
                {% endif %}
                {% if perms.secretsanta.manage %}
                    <a class="btn btn-warning" href="{% url 'secretsanta:applications' year.year %}" role="button">{% trans "Applications" %}</a>
                    <a class="btn btn-danger" href="{% url 'secretsanta:pairs' year.year %}" role="button"><span class="fa fas fa-skull-crossbones"></span> {% trans "Administer" %} <span class="fa fas fa-skull-crossbones"></span></a>
                {% endif %}
            </div>
        </div>
    {% endif %}
</div>